version: '3.1'

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
    volumes:
      - ./dist/training:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
